stages:
  - run-jobs

default:
  image: "$CI_REGISTRY_IMAGE:latest"

rust-check:
  stage: run-jobs
  script:
    - cargo check --all-features
    - cargo clippy --all-features --no-deps
    - cargo fmt -- --check
  when: always

rust-test:
  stage: run-jobs
  script:
    - cargo test --all --all-features
  when: always

pages:
  stage: run-jobs
  script:
    - cargo doc --workspace --no-deps --all-features
    - mkdir -p public
    - cp -r target/doc/* public/
    - echo '<meta http-equiv="refresh" content="0; url=rusteb">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
  when: always
