stages:
  - check
  - test
  - docs

variables:
  RUST_IMAGE: "gitlab-registry.cern.ch/mhermoso/pcie40-rs:latest"
  RUST_BACKTRACE: 1
  #HARDWARE_TESTS_DEVICE_NAME: "tdtel202_0"

# Common configuration to be extended
.rust_template:
  tags: [online_network, docker]
  image: ${RUST_IMAGE}

# Syntax and code quality check
rust-check:
  extends: .rust_template
  stage: check
  script:
    - cargo check --all-features --offline
    - cargo clippy --all-features --no-deps --offline # -- -D warnings
    - cargo fmt -- --check

# Run standard tests (excluding hardware tests)
rust-test:
  extends: .rust_template
  stage: test
  script:
    - cargo test --all --all-features --offline

# TODO: CHECK HOW TO PROPERLY DO HARDWARE TESTS
# Run tests including hardware tests
#rust-test-hardware:
  #extends: .rust_template
  #stage: test
  #script:
    #- cargo test --features hardware-tests
  #tags:
    #- online_network
    #- docker
    ##- pcie40-hardware # Add a specific tag for runners with the hardware

# Build and publish documentation to GitLab Pages
pages:
  extends: .rust_template
  stage: docs
  script:
    - cargo doc --no-deps --all-features --offline
    - mkdir -p public
    - cp -r target/doc/* public/
    - echo '<meta http-equiv="refresh" content="0; url=pcie40_rs/index.html">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master