stages:
  - run-jobs

variables:
  RUST_BACKTRACE: 1
  RUST_IMAGE: "$CI_REGISTRY_IMAGE:latest"
  #HARDWARE_TESTS_DEVICE_NAME: "tdtel202_0"

.deps_template:
  image: ${RUST_IMAGE}

.online_template:
  extends: .deps_template
  tags: [online_network, docker]

rust-check:
  extends: .deps_template
  stage: run-jobs
  script:
    - cargo check --all-features
    - cargo clippy --all-features --no-deps
    - cargo fmt -- --check
  when: always

rust-test:
  extends: .deps_template
  stage: run-jobs
  script:
    - cargo test --all --all-features --offline
  when: always

pages:
  extends: .deps_template
  stage: run-jobs
  script:
    - cargo doc --workspace --no-deps --all-features
    - mkdir -p public
    - cp -r target/doc/* public/
    - echo '<meta http-equiv="refresh" content="0; url=rusteb">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
  when: always
