services:
  rust-dev:
    platform: linux/amd64
    image: gitlab-registry.cern.ch/mhermoso/pcie40-rs:latest
    command: sleep infinity
    volumes:
      - ./:/app
    # Use privileged mode to access hardware
    privileged: true
    shm_size: 32gb

