pub mod completion_queue;
pub mod context;
pub mod devices;
pub mod global_unique_id;
pub mod memory_region;
pub mod prepared_queue_pair;
pub mod protection_domain;
pub mod queue_pair;
pub mod queue_pair_builder;
pub mod queue_pair_endpoint;
pub mod scatter_gather_element;
mod unsafe_member;
