use std::fmt::Debug;

use bytemuck::{Pod, Zeroable, bytes_of};
use thiserror::Error;
use tracing::warn;
use typed_builder::TypedBuilder;

use crate::{fragment::Fragment, fragment_type::FragmentType};
pub use time::UtcDateTime;

/// This struct defines an how the payload of an ODIN fragment looks like.
///
/// You can easily construct an odin payload using the [`OdinPayload::builder()`] method.
/// This is usually only necessary for testing purposes though.
///
/// It is defined [here](https://edms.cern.ch/ui/file/2100937/5/edms_2100937_raw_data_format_run3.pdf#page=12).
#[repr(C, packed)]
#[derive(Copy, Clone, Pod, Zeroable, Debug)]
pub struct OdinPayload {
    run_number: u32,
    event_type: u16,
    step_number: u16,
    gps_time: u64,
    tck: u32,
    partition_id: u32,
    misc: u32,
    orbit_id: u32,
    event_id: u64,
}

#[deny(clippy::cast_sign_loss)]
impl OdinPayload {
    /// The number of bunches that fit into LHC. This dictates the maximal number of bunch crossings.
    pub const BUNCH_PER_ORBIT: u16 = 3564;

    /// The version such fragments should have, as configured in an MFP.
    pub const FRAGMENT_VERSION: u8 = 7;

    /// The type such odin fragments should have.
    pub const FRAGMENT_TYPE: FragmentType = FragmentType::ODIN;

    /// This is the Run Number as set by the central ECS at the start of a run.
    pub fn run_number(self) -> u32 {
        self.run_number
    }

    /// This is a word that is generated by the SODIN instance to identify the type of an
    /// event. The exact definition of the numbers is to be agreed upon and it is defined on a set of
    /// configurable registers and processes inside the SODIN firmware.
    pub fn event_type(self) -> u16 {
        self.event_type
    }

    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    pub fn step_number(self) -> u16 {
        self.step_number
    }

    /// This is the absolute GPS time of an event with a resolution of roughly 100 µs.
    pub fn gps_time_raw(self) -> u64 {
        self.gps_time
    }

    pub fn gps_time(self) -> UtcDateTime {
        UtcDateTime::from_unix_timestamp_nanos(self.gps_time as i128 * 1000)
            .expect("Odin GPS time is valid")
    }

    /// This is the Trigger Configuration Key as set by the central ECS system.
    pub fn tck(self) -> u32 {
        self.tck
    }

    /// This is the Partition ID to which a specific SODIN instance belongs to.
    pub fn partition_id(self) -> u32 {
        self.partition_id
    }

    /// The orbit identifier is incremented on each turn of the LHC beams as marked by bunch
    /// crossing 0. The orbit number is reset on each start of run. Together with the Bunch ID they
    /// form an exact definition of the relative time of an event with respect to the start of run. It
    /// may be used as an alternative during times if the GPS time is not available.
    pub fn orbit_id(self) -> u32 {
        self.orbit_id
    }

    /// This is the global 64-bits Event ID that uniquely identify an event within a run. It
    /// increases monotonically and it is reset at every start run. The first event is identified by Event ID = 0.
    pub fn event_id(self) -> u64 {
        self.event_id
    }

    // == Misc ==

    /// This is the bunch crossing ID of the accepted event. It starts at 0 and wraps around at 3563.
    /// 12 bit values.
    pub fn bunch_id(self) -> u16 {
        (self.misc & ((1 << 12) - 1)) as u16
    }

    /// The expected bunch crossing type for `(beam1, beam2)`. `false` mean no beam, `true` means beam.
    /// It is produced by an internal sequencer which is loaded
    /// by the ECS system and it is based on the LHC filling scheme.
    pub fn bx_type(self) -> (bool, bool) {
        (self.misc >> 12 & 1 == 1, self.misc >> 13 & 1 == 1)
    }

    /// This single bit indicates if the current event was requested to be a Non-Zero Suppressed event.
    pub fn is_nzs_event(self) -> bool {
        (self.misc >> 14) & 1 == 1
    }

    /// In case of a Timing Alignment Event (TAE), the SODIN instance fires the acceptance of a window
    /// of bunch-crossings around the central trigger. This fields indicates the
    /// half-window size. If the value of this field is > 0 then the event associated is to be considered
    /// part of a TAE.
    pub fn tae_window(self) -> u8 {
        ((self.misc >> 16) & ((1 << 6) - 1)) as u8
    }

    /// This bit indicates if this particular event is to be considered the central trigger of a TAE window.
    pub fn tae_central(self) -> bool {
        self.misc >> 15 & 1 == 1
    }

    /// This bit indicates if this particular event is to be considered the first trigger of a TAE window.
    pub fn tae_first(self) -> bool {
        self.misc >> 27 & 1 == 1
    }

    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    pub fn step_run_enable(self) -> bool {
        self.misc >> 22 & 1 == 1
    }

    /// This field indicates the type of trigger that has been generated, encoded in 16 cases (4 bits).
    pub fn trigger_type(self) -> u8 {
        (self.misc >> 23 & 0xF) as u8
    }

    /// The calib type indicates what calibration command was sent at the same time as a calibration trigger (4 bits).
    pub fn calib_type(self) -> u8 {
        (self.misc >> 28 & 0xF) as u8
    }

    /// Returns a typed builder for constructing an OdinPayload.
    ///
    /// The following setter methods are required:
    /// - `event_id(u64)`
    /// - `event_type(u16)`
    /// - `run_number(u32)`
    /// - `orbit_id(u32)`
    /// - `bunch_id(u16)`
    /// - `partition_id(u32)`
    /// - `gps_time(UtcDateTime)`
    /// - `tck(u32)`
    /// - `trigger_type(u8)`
    ///
    /// The following setter methods are optional:
    /// - `step_number(u16)` (default: 0)
    /// - `bx_type((bool, bool))` (default: (true, true))
    /// - `is_nzs_event(bool)` (default: false)
    /// - `tae(window: u8, central: bool, first: bool)` (default: (0, false, false))
    /// - `step_run_enable(bool)` (default: false)
    /// - `calib_type(u8)` (default: 0)
    ///
    /// In the end, you can use the `build()` method to construct the OdinPayload, which may return an error if some fields are invalid.
    ///
    /// # Example
    /// ```rust
    /// use ebutils::odin::OdinPayload;
    /// use time::UtcDateTime;
    ///
    /// let odin = OdinPayload::builder()
    ///     .event_id(12345)
    ///     .bunch_id(4)
    ///     .event_type(5)
    ///     .run_number(6)
    ///     .gps_time(UtcDateTime::now())
    ///     .orbit_id(156)
    ///     .tck(5656)
    ///     .partition_id(2)
    ///     .trigger_type(5)
    ///     .build()
    ///     .unwrap();
    /// ```
    pub fn builder() -> OdinBuilder {
        OdinBuilderInternal::builder()
    }
}

impl AsRef<[u8]> for OdinPayload {
    fn as_ref(&self) -> &[u8] {
        bytemuck::bytes_of(self)
    }
}

impl From<OdinPayload> for Vec<u8> {
    fn from(value: OdinPayload) -> Self {
        value.as_ref().to_vec()
    }
}

/// Error type returned when casting a generic fragment into an Odin fragment fails.
#[derive(Debug, Error)]
pub enum FragmentCastError {
    /// The fragment does not mach the required one.
    #[error("Wrong fragment type: expected {expected} but got {got}")]
    WrongFragmentType { expected: FragmentType, got: u8 },
    /// The fragment type matches, but its size is wrong.
    #[error("Wrong fragment size: expected {expected} but got {got}")]
    WrongFragmentSize { expected: usize, got: usize },
    /// The fragment type matches, but the version is not supported.
    #[error("Unsupported fragment version: got {got} but only {supported} are supported")]
    WrongFragmentVersion { supported: String, got: u8 },
}

impl<'a> TryFrom<Fragment<'a>> for Fragment<'a, OdinPayload> {
    type Error = FragmentCastError;

    fn try_from(value: Fragment<'a>) -> Result<Self, Self::Error> {
        value.try_into_odin()
    }
}

impl<'a> From<Fragment<'a, OdinPayload>> for Fragment<'a> {
    fn from(value: Fragment<'a, OdinPayload>) -> Self {
        value.into_generic()
    }
}

impl<'a> Fragment<'a> {
    /// Tries to cast a generic fragment into an Odin fragment.
    ///
    /// If successful, this allows to access the odin-specific fields of the payload.
    /// # Example
    /// ```
    /// # use ebutils::{fragment::{Fragment}, FragmentType, odin::OdinPayload, source_id::{SourceId, SubDetector}};
    /// # let foo = || Fragment::new(
    /// #       FragmentType::Odin as _,
    /// #       1,
    /// #        42,
    /// #        SourceId::new_odin(1),
    /// #        &[0u8; std::mem::size_of::<OdinPayload>()][..],
    /// #    );
    /// let fragment: Fragment<'_> = foo(); // getting a fragment from somewhere
    ///
    /// let odin_fragment: Fragment<'_, OdinPayload> = fragment.try_into_odin().unwrap();
    ///
    /// assert_eq!(odin_fragment.payload().event_id(), 0);
    /// ```
    pub fn try_into_odin(&self) -> Result<Fragment<'a, OdinPayload>, FragmentCastError> {
        if !self
            .fragment_type_parsed()
            .is_some_and(|t| t == FragmentType::ODIN)
        {
            return Err(FragmentCastError::WrongFragmentType {
                expected: FragmentType::ODIN,
                got: self.fragment_type_raw(),
            });
        }

        if self.version() != OdinPayload::FRAGMENT_VERSION {
            warn!(
                "Encountered unsupported fragment version {} for odin fragment",
                self.version(),
            );
            return Err(FragmentCastError::WrongFragmentVersion {
                got: self.version(),
                supported: OdinPayload::FRAGMENT_VERSION.to_string(),
            });
        }

        let odin = bytemuck::try_from_bytes(self.payload_bytes()).map_err(|e| match e {
            bytemuck::PodCastError::SizeMismatch => {
                warn!(
                    "Encountered wrong fragment size of {} (expected {}) for odin fragment (version {})",
                    self.payload_bytes().len(),
                    size_of::<OdinPayload>(),
                    self.version()
                );
                FragmentCastError::WrongFragmentSize {
                    expected: size_of::<OdinPayload>(),
                    got: self.payload_bytes().len(),
                }
            }
            e => panic!("{e:?}"),
        })?;

        Ok(self.map_payload(|_| odin))
    }
}

/// Casts an Odin fragment back into a generic fragment.
impl<'a> Fragment<'a, OdinPayload> {
    pub fn into_generic(self) -> Fragment<'a> {
        self.map_payload(bytes_of)
    }
}

impl<'a> Debug for Fragment<'a, OdinPayload> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Fragment<OdinPayload>")
            .field("type", &self.fragment_type_parsed())
            .field("version", &self.version())
            .field("event_id", &self.event_id())
            .field("source_id", &self.source_id())
            .field("data", &self.payload())
            .finish()
    }
}

#[derive(TypedBuilder)]
#[builder(builder_type(name=OdinBuilder, vis="pub"), build_method(into = Result<OdinPayload, OdinBuilderError>))]
struct OdinBuilderInternal {
    /// This is the Run Number as set by the central ECS at the start of a run.
    run_number: u32,
    /// This is a word that is generated by the SODIN instance to identify the type of an
    /// event. The exact definition of the numbers is to be agreed upon and it is defined on a set of
    /// configurable registers and processes inside the SODIN firmware.
    event_type: u16,
    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    #[builder(default)]
    step_number: u16,

    /// This is the absolute GPS time of an event with a resolution of roughly 100 µs.
    #[builder(setter(transform = |gps_time: UtcDateTime| u64::try_from(gps_time.unix_timestamp_nanos() / 1_000).expect("time fits into u64")))]
    gps_time: u64,
    /// This is the Trigger Configuration Key as set by the central ECS system.
    tck: u32,
    /// This is the Partition ID to which a specific SODIN instance belongs to.
    partition_id: u32,
    /// The orbit identifier is incremented on each turn of the LHC beams as marked by bunch
    /// crossing 0. The orbit number is reset on each start of run. Together with the Bunch ID they
    /// form an exact definition of the relative time of an event with respect to the start of run. It
    /// may be used as an alternative during times if the GPS time is not available.
    orbit_id: u32,
    /// This is the global 64-bits Event ID that uniquely identify an event within a run. It
    /// increases monotonically and it is reset at every start run. The first event is identified by Event ID = 0.
    event_id: u64,
    // misc
    /// This is the bunch crossing ID of the accepted event. It starts at 0 and wraps around after 3563 (3564 possible values).
    bunch_id: u16,
    /// The expected bunch crossing type for `(beam1, beam2)`. `false` mean no beam, `true` means beam.
    /// It is produced by an internal sequencer which is loaded
    /// by the ECS system and it is based on the LHC filling scheme.
    #[builder(default = (true,true))]
    bx_type: (bool, bool),
    /// This single bit indicates if the current event was requested to be a Non-Zero Suppressed event.
    #[builder(setter(strip_bool))]
    is_nzs_event: bool,
    /// In case of a Timing Alignment Event (TAE), the SODIN instance fires the acceptance of a window
    /// of bunch-crossings around the central trigger. This fields indicates the
    /// half-window size. If the value of this field is > 0 then the event associated is to be considered
    /// part of a TAE.
    ///
    /// `central`: This bit indicates if this particular event is to be considered the central trigger of a TAE window. \
    /// `first`: This bit indicates if this particular event is to be considered the first trigger of a TAE window.
    #[builder(default, setter(transform = |window: u8, central: bool, first: bool| Some(TaeConfig { window, central, first })))]
    tae: Option<TaeConfig>,
    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    #[builder(setter(strip_bool))]
    step_run_enable: bool,
    /// This field indicates the type of trigger that has been generated, encoded in 16 cases (4 bits).
    trigger_type: u8,
    /// The calib type indicates what calibration command was sent at the same time as a calibration trigger (4 bits).
    #[builder(default)]
    calib_type: u8,
}

struct TaeConfig {
    window: u8,
    central: bool,
    first: bool,
}

impl From<OdinBuilderInternal> for Result<OdinPayload, OdinBuilderError> {
    fn from(builder: OdinBuilderInternal) -> Self {
        let mut misc: u32 = 0;
        if builder.bunch_id >= OdinPayload::BUNCH_PER_ORBIT {
            return Err(OdinBuilderError::BunchIdTooLarge(builder.bunch_id));
        }
        misc |= (builder.bunch_id as u32) & ((1 << 12) - 1);

        misc |= (builder.bx_type.0 as u32) << 12;
        misc |= (builder.bx_type.1 as u32) << 13;
        misc |= (builder.is_nzs_event as u32) << 14;

        if let Some(tae) = builder.tae {
            if tae.window >= (1 << 6) {
                return Err(OdinBuilderError::TaeWindowTooLarge(tae.window));
            }
            misc |= (tae.central as u32) << 15;
            misc |= (tae.window as u32 & ((1 << 6) - 1)) << 16;
            misc |= (tae.first as u32) << 27;
        }

        misc |= (builder.step_run_enable as u32) << 22;
        if builder.trigger_type >= 16 {
            return Err(OdinBuilderError::TriggerTypeTooLarge(builder.trigger_type));
        }
        misc |= (builder.trigger_type as u32 & 0xF) << 23;
        if builder.calib_type >= 16 {
            return Err(OdinBuilderError::CalibTypeTooLarge(builder.calib_type));
        }
        misc |= (builder.calib_type as u32 & 0xF) << 28;

        Ok(OdinPayload {
            run_number: builder.run_number,
            event_type: builder.event_type,
            step_number: builder.step_number,
            gps_time: builder.gps_time,
            tck: builder.tck,
            partition_id: builder.partition_id,
            misc,
            orbit_id: builder.orbit_id,
            event_id: builder.event_id,
        })
    }
}

#[derive(Debug, Error)]
pub enum OdinBuilderError {
    #[error("Bunch ID too large: {0}, must be less than {top}, the maximally possible number of bunches pre orbit", top = OdinPayload::BUNCH_PER_ORBIT)]
    BunchIdTooLarge(u16),
    #[error("Trigger type too large: {0}, must be less than 16")]
    TriggerTypeTooLarge(u8),
    #[error("Calib type too large: {0}, must be less than 16")]
    CalibTypeTooLarge(u8),
    #[error("TAE window too large: {0}, must be less than {top}", top = 1 << 6)]
    TaeWindowTooLarge(u8),
}

/// Just some dummy payload used for testing.
#[doc(hidden)]
pub fn dummy_odin_payload(event_id: u64) -> OdinPayload {
    OdinPayload::builder()
        .event_id(event_id)
        .bunch_id(4)
        .event_type(5)
        .run_number(6)
        .gps_time(UtcDateTime::now())
        .orbit_id(156)
        .tck(5656)
        .partition_id(2)
        .trigger_type(5)
        .build()
        .expect("valid")
}

#[cfg(test)]
mod test {
    use time::UtcDateTime;

    use crate::{
        fragment_type::FragmentType,
        source_id::{SourceId, SubDetector},
    };

    #[test]
    fn test_builder() {
        let time = UtcDateTime::now();
        let odin = super::OdinPayload::builder()
            .event_id(12345)
            .bunch_id(4)
            .event_type(5)
            .run_number(6)
            .gps_time(time)
            .orbit_id(156)
            .tck(5656)
            .partition_id(2)
            .trigger_type(5)
            .build()
            .unwrap();

        assert_eq!(odin.event_id(), 12345);
        assert_eq!(odin.run_number(), 6);
        assert_eq!(odin.bunch_id(), 4);
        assert_eq!(odin.event_type(), 5);
        assert_eq!(
            odin.gps_time_raw(),
            (time.unix_timestamp_nanos() / 1_000).try_into().unwrap()
        );
        assert!(!odin.tae_central());
        assert!(!odin.tae_first());
        assert_eq!(odin.tae_window(), 0);
        assert!(odin.bx_type().1);
        assert!(odin.bx_type().0);
        assert_eq!(odin.orbit_id(), 156);
        assert_eq!(odin.tck(), 5656);
        assert_eq!(odin.partition_id(), 2);
        assert_eq!(odin.trigger_type(), 5);
        assert!(!odin.is_nzs_event());
        assert_eq!(odin.tae_window(), 0);
        assert_eq!(odin.step_number(), 0);
        assert_eq!(odin.calib_type(), 0);
        assert_eq!(odin.partition_id(), 2);
        assert!(!odin.step_run_enable());
    }

    #[test]
    fn test_odin_fragment_cast() {
        use crate::fragment::Fragment;

        use super::dummy_odin_payload;

        let odin_payload = dummy_odin_payload(12345);
        let fragment: Fragment<'_, super::OdinPayload> = Fragment::new(
            FragmentType::ODIN as _,
            7,
            0,
            SourceId::new(SubDetector::Odin, 0),
            &odin_payload,
        );

        let generic_fragment: Fragment<'_> = fragment.into();
        let casted_fragment = generic_fragment.try_into_odin().unwrap();

        assert_eq!(casted_fragment.payload().event_id(), 12345);
        assert_eq!(casted_fragment.payload().run_number(), 6);
        assert_eq!(casted_fragment.payload().bunch_id(), 4);
        assert_eq!(casted_fragment.payload().event_type(), 5);
    }
}
