/// See <https://edms.cern.ch/ui/file/2100937/5/edms_2100937_raw_data_format_run3.pdf#page=12>.
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct OdinFragment {
    run_number: u32,
    event_type: u16,
    step_number: u16,
    gps_time: u64,
    tck: u32,
    partition_id: u32,
    misc: u32,
    orbit_id: u32,
    event_id: u64,
}

#[deny(clippy::cast_sign_loss)]
impl OdinFragment {
    /// This is the Run Number as set by the central ECS at the start of a run.
    pub fn run_number(self) -> u32 {
        self.run_number
    }

    /// This is a word that is generated by the SODIN instance to identify the type of an
    /// event. The exact definition of the numbers is to be agreed upon and it is defined on a set of
    /// configurable registers and processes inside the SODIN firmware.
    pub fn event_type(self) -> u16 {
        self.event_type
    }

    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    pub fn step_number(self) -> u16 {
        self.step_number
    }

    /// This is the absolute GPS time of an event with a resolution of roughly 100 µs.
    pub fn gps_time(self) -> u64 {
        self.gps_time
    }

    /// This is the Trigger Configuration Key as set by the central ECS system.
    pub fn trigger_config_key(self) -> u32 {
        self.tck
    }

    /// This is the Partition ID to which a specific SODIN instance belongs to.
    pub fn partition_id(self) -> u32 {
        self.partition_id
    }

    /// The orbit identifier is incremented on each turn of the LHC beams as marked by bunch
    /// crossing 0. The orbit number is reset on each start of run. Together with the Bunch ID they
    /// form an exact definition of the relative time of an event with respect to the start of run. It
    /// may be used as an alternative during times if the GPS time is not available.
    pub fn orbit_id(self) -> u32 {
        self.orbit_id
    }

    /// this is the global 64-bits Event ID that uniquely identify an event within a run. It
    /// increases monotonically and it is reset at every start run. The first event is identified by Event ID = 0.
    pub fn event_id(self) -> u64 {
        self.event_id
    }

    // == Misc ==

    /// This is the bunch crossing ID of the accepted event. It starts at 0 and wraps around at 3563.
    /// 12 bit values.
    pub fn bunch_id(self) -> u16 {
        (self.misc & ((1 << 12) - 1)) as u16
    }

    /// The expected bunch crossing type for `(beam1, beam2)`. `false` mean no beam, `true` means beam.
    /// It is produced by an internal sequencer which is loaded
    /// by the ECS system and it is based on the LHC filling scheme.
    pub fn bx_type(self) -> (bool, bool) {
        (self.misc >> 12 & 1 == 1, self.misc >> 13 & 1 == 1)
    }

    /// This single bit indicates if the current event was requested to be a Non-Zero Suppressed event.
    pub fn is_nzs_event(self) -> bool {
        (self.misc >> 14) & 1 == 1
    }

    /// In case of a Timing Alignment Event (TAE), the SODIN instance fires the acceptance of a window
    /// of bunch-crossings around the central trigger. This fields indicates the
    /// half-window size. If the value of this field is > 0 then the event associated is to be considered
    /// part of a TAE.
    pub fn tae_window(self) -> u8 {
        ((self.misc >> 16) & ((1 << 6) - 1)) as u8
    }

    /// This bit indicates if this particular event is to be considered the central trigger of a TAE window.
    pub fn tae_central(self) -> bool {
        self.misc >> 15 & 1 == 1
    }

    /// This bit indicates if this particular event is to be considered the first trigger of a TAE window.
    pub fn tae_first(self) -> bool {
        self.misc >> 27 & 1 == 1
    }

    /// This field is used only when performing scans or special data taking runs where
    /// all events are in the same run, but conditions are changed at every step. The change in step
    /// number is driven by the central ECS.
    pub fn step_run_enable(self) -> bool {
        self.misc >> 22 & 1 == 1
    }

    /// This field indicates the type of trigger that has been generated, encoded in 16 cases (4 bits).
    pub fn trigger_type(self) -> u8 {
        (self.misc >> 23 & 0xF) as u8
    }

    /// The calib type indicates what calibration command was sent at the same time as a calibration trigger (4 bits).
    pub fn calib_type(self) -> u8 {
        (self.misc >> 28 & 0xF) as u8
    }
}
